title: Site

pages: false

fields:
  title:
    label: Title
    type:  text

  author:
    label: Author
    type:  text

  description:
    label: Description
    type:  textarea

  copyright:
    label: Copyright
    type:  textarea

  twitter:
    label: Twitter
    icon: twitter
    type: url
    width: 1/2

  facebook:
    label: Facebook
    icon: facebook-f
    type: url
    width: 1/2

  instagram:
    label: Instagram
    icon: instagram
    type: url
    width: 1/2
